services:
  patient_app_web:
    container_name: ${PATIENT_APP_CONTAINER_NAME:-patient_app_web}
    restart: unless-stopped
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        ENV: ${PATIENT_APP_ENV_FILE:-env/prod_dev_env.json}
        NGINX_FILE: ${PATIENT_APP_NGINX_FILE:-generated/default_ec2.conf}
    ports:
      - "${PATIENT_APP_HTTP_PORT:-80}:80"
      - "${PATIENT_APP_HTTPS_PORT:-443}:443"
    volumes:
      - /var/www/.well-known/acme-challenge:/var/www/.well-known/acme-challenge
      - /etc/letsencrypt/live/${PATIENT_APP_TLS_DOMAIN}/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/${PATIENT_APP_TLS_DOMAIN}/privkey.pem:/etc/ssl/private/privkey.pem:ro
