server {
    listen 80;
    listen [::]:80;
    server_name 44.193.233.102;

    location / {
        return 301 https://rpm.gheit.co$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name rpm.gheit.co;

    location / {
        return 301 https://rpm.gheit.co$request_uri;
    }
}


server {
    listen 443 ssl;
    server_name rpm.gheit.co;

    ssl_certificate /etc/ssl/certs/fullchain.pem;
    ssl_certificate_key /etc/ssl/private/privkey.pem;

    root /usr/share/nginx/html;
    error_page 497 301 =307  https://rpm.gheit.co$request_uri;

    # Allow access to .well-known
    location ~ ^/.well-known/acme-challenge/ {
        allow all;
        root /var/www/;
    }

    # Restrict access to other dot files
    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
