// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIhfHM01UasR_cwOomBRF9c1vGRRVYzc8',
    appId: '1:828975767865:web:6c010017ebc30bc7cfc8e8',
    messagingSenderId: '828975767865',
    projectId: 'rook-51b6a',
    authDomain: 'rook-51b6a.firebaseapp.com',
    storageBucket: 'rook-51b6a.firebasestorage.app',
    measurementId: 'G-HYQ98BH29M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk5o5Of7l69xZZ8oRXTEMYxgdV1k_I0ow',
    appId: '1:828975767865:android:b859a26076938a88cfc8e8',
    messagingSenderId: '828975767865',
    projectId: 'rook-51b6a',
    storageBucket: 'rook-51b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl-4XfPEuHl1QbJKSj7IH0LeqjUhTtdy8',
    appId: '1:828975767865:ios:6677e73d4980d83fcfc8e8',
    messagingSenderId: '828975767865',
    projectId: 'rook-51b6a',
    storageBucket: 'rook-51b6a.firebasestorage.app',
    iosBundleId: 'co.gheit.vitalcarex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq9Dm2kZHf7FdP-VYv5C24T_LwbbxRutg',
    appId: '1:886089009947:ios:c8da4a5868568e23e4e1be',
    messagingSenderId: '886089009947',
    projectId: 'opal-opensource',
    databaseURL: 'https://opal-opensource-default-rtdb.firebaseio.com',
    storageBucket: 'opal-opensource.firebasestorage.app',
    iosBundleId: 'com.example.patientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQbjfgAh9xGeEJmFuTDaKJsFx9SKQWNlY',
    appId: '1:886089009947:web:8f6d1c804846dffde4e1be',
    messagingSenderId: '886089009947',
    projectId: 'opal-opensource',
    authDomain: 'opal-opensource.firebaseapp.com',
    databaseURL: 'https://opal-opensource-default-rtdb.firebaseio.com',
    storageBucket: 'opal-opensource.firebasestorage.app',
  );
}
